spring.application.name=Project-Management-Tool-for-Freelancers
spring.datasource.url=jdbc:mysql://localhost:3306/freelance_manager
spring.datasource.username=root
spring.datasource.password=Jashvanth25@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=your_secret_key_here_should_be_at_least_32_characters_long
jwt.expiration=86400